# Generated by Django 4.0.2 on 2024-10-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="special_offer",
            field=models.BooleanField(default=False),
        ),
    ]
