# Generated by Django 4.0.2 on 2024-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_discount_price_product_special_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="special_offer",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
