# Generated by Django 4.0.2 on 2024-10-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_product_discount_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
