# Generated by Django 4.0.2 on 2024-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_cartitem_user_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
