# Generated by Django 4.0.2 on 2024-11-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_category_image_product_image_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
