# Generated by Django 4.0.2 on 2024-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
    ]
