# Generated by Django 4.0.2 on 2024-11-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_order_address_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
