# Generated by Django 4.0.2 on 2024-11-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0012_alter_order_address_alter_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المعالجة"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
