# Generated by Django 4.0.2 on 2024-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
