# Generated by Django 4.0.2 on 2024-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_notification_created_at_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
