# Generated by Django 4.0.2 on 2025-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
