# Generated by Django 4.0.2 on 2025-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", " Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
