# Generated by Django 4.0.2 on 2025-01-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity_remaining",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
