# Generated by Django 4.0.2 on 2025-01-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0028_deliveryperson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryperson",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="deliveryperson",
            name="name",
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
