# Generated by Django 4.0.2 on 2025-01-06 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0029_remove_deliveryperson_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="status",
            field=models.CharField(
                choices=[("available", "متاح"), ("busy", "مشغول")],
                default="available",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryperson",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
