# Generated by Django 4.0.2 on 2025-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0030_deliveryperson_name_deliveryperson_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
