# Generated by Django 4.0.2 on 2025-01-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0033_remove_deliveryperson_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shop.deliveryperson",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryperson",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="shop.order",
            ),
        ),
    ]
