# Generated by Django 4.0.2 on 2025-01-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0034_order_delivery_person_alter_deliveryperson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="order_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
