# Generated by Django 4.0.2 on 2025-01-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_deliveryperson_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryperson",
            name="order_status",
            field=models.CharField(default="في الطريق", max_length=255),
        ),
    ]
