# Generated by Django 4.0.2 on 2025-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0036_alter_deliveryperson_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="cancelled",
                max_length=20,
            ),
        ),
    ]
