# Generated by Django 4.0.2 on 2025-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0039_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(default="Normal", max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="response_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=100,
            ),
        ),
    ]
