# Generated by Django 4.0.2 on 2025-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0040_ticket_assigned_to_ticket_notes_ticket_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="response_time",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(default="Open", max_length=100),
        ),
    ]
